version: '3.9'
services:
  web:
    build: .
    ports:
      - '4000:4000'
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}
