export const DATA = [
  {
    title: '지구를 구하라 천연수세미 코코넛',
    amount: '19000',
    like: '12',
    rating: '2.5',
    review: '13',
  },
  {
    title: '제로웨이스트 주방용품키트',
    amount: '23000',
    like: '23',
    rating: '2.3',
    review: '2',
  },
  {
    title: '천연 지팡이 야자솔',
    amount: '19700',
    like: '11',
    rating: '1.3',
    review: '29',
  },
  {
    title: '친환경 살림살이 세트',
    amount: '1800',
    like: '12',
    rating: '3.4',
    review: '3',
  },
  {
    title: '동구밭 고체설거지 비누',
    amount: '32000',
    like: '54',
    rating: '1.2',
    review: '34',
  },
  {
    title: '재생지 월간보드 12장',
    amount: '1700',
    like: '12',
    rating: '4.5',
    review: '12',
  },
  {
    title: '무형광 무표백 2겹 수건',
    amount: '56000',
    like: '54',
    rating: '6.6',
    review: '8',
  },
  {
    title: '샴푸바 3가지 고체 샴푸',
    amount: '18900',
    like: '4',
    rating: '3.3',
    review: '13',
  },
  {
    title: '먼지없는 친환경 대나무 3겹화장지 18롤',
    amount: '32800',
    like: '67',
    rating: '3.1',
    review: '12',
  },
  {
    title: '오리지널 고체치약 30정입',
    amount: '4800',
    like: '45',
    rating: '4.1',
    review: '4',
  },
  {
    title: '친환경 곤약스펀지 얼굴 세안용',
    amount: '15900',
    like: '41',
    rating: '2.3',
    review: '6',
  },
  {
    title: '올바른 린스바, 제로 플라스틱',
    amount: '17900',
    like: '26',
    rating: '3.6',
    review: '54',
  },
  {
    title: '인체무해 친환경제품 녹말 이쑤시개 300P',
    amount: '1310',
    like: '25',
    rating: '4.9',
    review: '11',
  },
  {
    title: '스텐빨대 다회용 빨대',
    amount: '6350',
    like: '25',
    rating: '2.2',
    review: '7',
  },
];
